### ISSUE TITLE
Using TextArea with react-hook-form

### ISSUE THREAD

**Issue by eirikm** [fabric-ds/issues#22]
The types:

`type TextAreaProps = {
    label: string;
    name: string;
    error?: FieldError;
    validationText?: string;
    registerReturn: UseFormRegisterReturn;
    extraClasses?: string;
};
`

usage:
`
        <TextArea
            className={extraClasses ?? ''}
            label={label}
            helpText={validationText}
            invalid={!!error}
            {...registerReturn}
        />
`

I get the following error message:

TypeError: l is null
    Qr useTextAreaHeight.ts:80
    er source.production.js:124
    Rr source.production.js:160
    unstable_runWithPriority source.production.js:24
    kt source.production.js:58
    Mr source.production.js:160
    vr source.production.js:144
    St source.production.js:59
    unstable_runWithPriority source.production.js:24
    kt source.production.js:58
    St source.production.js:59
    Tt source.production.js:58
    Ju source.production.js:222
    Sn source.production.js:91
    useRemoteData RemoteData.ts:147
    match index.es.js:162
    useRemoteData RemoteData.ts:145
    promise callback*ResultAsync.prototype.then index.es.js:298
    useRemoteData RemoteData.ts:144
    er source.production.js:124
    Rr source.production.js:160
    unstable_runWithPriority source.production.js:24
    kt source.production.js:58
    Mr source.production.js:160
    Or source.production.js:160
    g source.production.js:15
    onmessage source.production.js:23
    EventHandlerNonNull* source.production.js:23
    <anonymous> source.production.js:31
source.production.js:123:23

**Comment by eirikm** [comment]
"@fabric-ds/react@^0.0.11":
  version "0.0.11"
  resolved "https://registry.yarnpkg.com/@fabric-ds/react/-/react-0.0.11.tgz#b68eaea1fad72fbc785d78354cbb5c28ca459e73"
  integrity sha512-d19Up/aRCYf3pgUMDdps2jyJ+1hKHqaXSrFq2zxb0k5FTLgmWdXryy8AQ89NlpKGjsDNOZ1356nEcYCO2VdKew==
  dependencies:
    "@chbphone55/classnames" "^2.0.0"
    d3-scale "^4.0.2"
    react-focus-lock "^2.5.2"
    react-spring "^8.0.27"
    react-use-gesture "^9.1.3"
    resize-observer-polyfill "^1.5.1"
    scroll-doctor "^0.9.1"

**Comment by vsandvold** [comment]
I believe this is related to the fix for merging refs in the TextArea component, which @benja worked on here https://github.com/fabric-ds/react/pull/63 (also reported here https://github.com/fabric-ds/react/issues/56).

You could try updating to the latest version of `fabric-ds/react`, which is currently on `1.0.2`.

**Comment by benja** [comment]
Did updating to a newer version fix your issue, @eirikm?

I need a bit more details regarding your use case and see some more code in order to properly assist with this. Spreading an object onto the TextArea component won't work unless we forward this onto the correct element inside the component. It looks to me like you are trying to add some props to the underlying textarea-element?

**Comment by benja** [comment]
Closing as there has been no further comments. Feel free to reopen if issue persists.
